version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
