version: "3.9"
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: python manage.py runserver 0.0.0.0:${PORT}
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.2-alpine
    restart: unless-stopped
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
  data:
